apiVersion: v1
kind: Service
metadata:
  name: speckle-preview-service-metrics
  namespace: {{ .Values.namespace }}
  labels:
{{ include "preview_service.labels" . | indent 4 }}
spec:
  selector:
{{ include "preview_service.selectorLabels" . | indent 4 }}
  ports:
    - name: web
      port: 9094
      protocol: TCP
      targetPort: metrics
