apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: speckle
build:
  platforms:
    - 'linux/amd64'
  artifacts:
    - image: speckle/speckle-frontend
      context: .
      custom:
        buildCommand: sh ./utils/skaffold/buildx.sh ./packages/frontend/Dockerfile
        dependencies:
          dockerfile:
            path: ./packages/frontend/Dockerfile
    - image: speckle/speckle-server
      context: .
      custom:
        buildCommand: sh ./utils/skaffold/buildx.sh ./packages/server/Dockerfile
        dependencies:
          dockerfile:
            path: ./packages/server/Dockerfile
    - image: speckle/speckle-preview-service
      context: .
      custom:
        buildCommand: sh ./utils/skaffold/buildx.sh ./packages/preview-service/Dockerfile
        dependencies:
          dockerfile:
            path: ./packages/preview-service/Dockerfile
    - image: speckle/speckle-webhook-service
      context: .
      docker:
        dockerfile: ./packages/webhook-service/Dockerfile
        cacheFrom:
          - 'speckle/speckle-webhook-service'
    - image: speckle/speckle-fileimport-service
      context: .
      docker:
        dockerfile: ./packages/fileimport-service/Dockerfile
        cacheFrom:
          - 'speckle/speckle-fileimport-service'
    - image: speckle/speckle-monitor-deployment
      context: .
      docker:
        dockerfile: ./utils/monitor-deployment/Dockerfile
        cacheFrom:
          - 'speckle/speckle-monitor-deployment'
  local:
    push: false
    useBuildkit: true
    concurrency: 20
deploy:
  kubeContext: kind-speckle
  helm:
    releases:
      - name: speckle-server
        chartPath: ./utils/helm/speckle-server
        artifactOverrides:
          docker_image_tag: speckle/speckle-frontend
          frontend: speckle/speckle-frontend
          preview-service: speckle/speckle-preview-service
        imageStrategy:
          helm: {}
        setValueTemplates:
          docker_image_tag: '{{.IMAGE_TAG}}'
        valuesFiles:
          - utils/kind/local.values.yaml
