apiVersion: v1
kind: Service
metadata:
  name: speckle-monitoring-metrics
  namespace: {{ .Values.namespace }}
  labels:
{{ include "monitoring.labels" . | indent 4 }}
spec:
  selector:
{{ include "monitoring.selectorLabels" . | indent 4 }}
  ports:
    - name: web
      port: 9092
      protocol: TCP
      targetPort: metrics
